[build]
    builder = "NIXPACKS"

[deploy]
    startCommand            = "bun src/index.ts"
    healthcheckPath         = "/healthz"
    healthcheckTimeout      = 10
    restartPolicyType       = "ON_FAILURE"
    restartPolicyMaxRetries = 3
